apiVersion: v1
kind: Service
metadata:
  name: echo-parent
  namespace: echo-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3333
  selector:
    app: echo-parent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-parent
  namespace: echo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-parent
  template:
    metadata:
      labels:
        app: echo-parent
    spec:
      containers:
      - name: echo-parent-container
        image: rianfowler/echo-parent
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-demo